### ISSUE TITLE
Recopilación de datos

### ISSUE THREAD

**Issue by urieluard** [prope-2020-gh-classroom/practica-final-por-equipos-verano-2020-itam-urieluard#2]
- [x] Demanda horaria de la región occidente del país en el periodo Septiembre 2017 a Julio 2020.
- [x] Demanada cada 2 segundos para los siguientes periodos:
     - 24 horas en día de verano.
     - 24 horas en día de invierno.

**Comment by lecepe00** [comment]
Información recopilada para los periodos mencionados.
