### ISSUE TITLE
Modelos propuestos

### ISSUE THREAD

**Issue by urieluard** [prope-2020-gh-classroom/practica-final-por-equipos-verano-2020-itam-urieluard#4]
- [x] Definir modelo que se adecue al comportamiento observado para hacer predicciones
     - Polinomios de grado n, con la función polyfit.
     - Polinomios piecewise (splines cúbicos), con la función interp1d.

- [x] Modelo para calcular energía (área bajo la curva de demanda) 
     - Integrando funciones de polinomios de varios grados.
     - Integrando por medio de trapecios con la función trapz.
     - Calculando el área bajo la curva, considerando la altura media de la demanda.

**Comment by lecepe00** [comment]
Se realizaron los modelos descritos para la interpolación/predicción, y para el cálculo del área bajo la curva.
