### ISSUE TITLE
Análisis y validación de modelos obtenidos

### ISSUE THREAD

**Issue by urieluard** [prope-2020-gh-classroom/practica-final-por-equipos-verano-2020-itam-urieluard#5]
- [x] Validación y pruebas del modelo de interpolación y predicción
     - Polinomios de grado n, con la función polyfit.
     - Polinomios piecewise (splines cúbicos), con la función interp1d.

- [x] Validación y pruebas del modelo de integración
     - Integrando funciones de polinomios de varios grados.
     - Integrando por medio de trapecios con la función trapz.
     - Calculando el área bajo la curva, considerando la altura media de la demanda.

**Comment by lecepe00** [comment]
Se evaluaron los distintos modelos para interpolación/predicción, y el cálculo del área bajo la curva.
